The power of parallel Computing
========================================================



?proc.time

"The ‘user time’ is the CPU time charged for the execution of user instructions of the calling process. The ‘system time’ is the CPU time charged for execution by the system on behalf of the calling process."


```{r load_data, echo=FALSE, results='hide'}
rm(list=ls())
load(file = "/media/truecrypt2/ORP2/HIC/SSS/Images/post_rxhcu_wt.RData")
```

```{r recode, echo=FALSE, results='hide'}
post_rxhcu_wt$treatment <- ifelse (post_rxhcu_wt$rcat1 == "iclra", 0, 1)
post_rxhcu_wt$gender2 <- ifelse (post_rxhcu_wt$gender == "F", 0, 1)
```

```{r mask_data_names, echo=FALSE, results='hide'}
xdf <- post_rxhcu_wt
xdf$ycol <- xdf$rcat1
xdf$ycol <- ifelse(xdf$ycol == "iclra", "cat1", "cat2")
```
First open R, then is needed to load the desire package
```{r library_boot}
library(boot)
library(parallel)
```

```{r function4boot}
mean4boot <- function (data, index, maxit){
	data <- data[index,]
	stat <- mean(data[data$ycol == "cat1",]$outpatient)
	stat
}
```
1 CPU
```{r cpu_1}
system.time (boot(xdf, statistic = mean4boot,	R = 50000, maxit = 100,
                  ncpus = 1, parallel = "multicore"), gcFirst = TRUE)
```
2 CPU
```{r cpu_2}
system.time (boot(xdf, statistic = mean4boot,  R = 50000, maxit = 100,
                  ncpus = 2, parallel = "multicore"), gcFirst = TRUE)
```
3 CPU
```{r cpu_3}
system.time (boot(xdf, statistic = mean4boot,  R = 50000, maxit = 100,
                  ncpus = 3, parallel = "multicore"), gcFirst = TRUE)
```

4 CPU
```{r cpu_4}
system.time (boot(xdf, statistic = mean4boot,  R = 50000, maxit = 100,
                  ncpus = 4, parallel = "multicore"), gcFirst = TRUE)
```



