---
title: "Prevalence Trend Plot App"
author: "José A. Bartolomei-Díaz, PhD - Outcome Project"
date: "March 21, 2015"
output: html_document
---

Countries and Institutions either public or privates have goals.  To achieve those goals there are a set of objectives and strategies that needs to be conducted.  Nevertheless, all implemented strategies are not relevant if specific outcomes (or performance measures) are not measured over time.  An example follows.  The World Health Organization (WHO) alert the international community that Non-communicable diseases (NCD) were responsible for 38 million (68\%) of the world’s 56 million deaths in 2012. More than 40\% of them (16 million) were premature deaths under age 70 years. Almost three quarters of all NCD deaths (28 million), and the majority of premature deaths (82\%), occur in low- and middle-income countries.  To guide Countries toward a better health and quality of life were set nine global targets (performance measures) for prevention and control of noncommunicable diseases to be attained by 2025.

Those are:

- Global target 1: A 25\% relative reduction in overall mortality from cardiovascular diseases, cancer, diabetes or chronic respiratory diseases 

 - Global target 2: At least 10\% relative reduction in the harmful use of alcohol as appropriate, within the national context

- Global target 3: A 10\% relative reduction in the prevalence of insufficient physical activity 

- Global target 4: A 30\% relative reduction in the mean population intake of salt /sodium

- Global target 5: A 30\% relative reduction in prevalence of current tobacco use in persons aged 15+ years 

- Global target 6: A 25\% relative reduction in the prevalence of raised blood pressure, or contain the prevalence of raised blood pressure, according to national circumstances 

- Global target 7: Halt the rise in diabetes and obesity 

- Global target 8: At least 50\% of eligible people receive drug therapy and counselling (including glycaemic control) to prevent heart attacks and strokes.

- Global target 9: An 80\% availability of the affordable basic technologies and essential medicines, including generics, required to treat major noncommunicable diseases in both public and private facilities

At Outcome Project have develop a web application were you will be able perceive what is to follow important health outcomes at

**http://www.outcomeproject.com/outcomes**

At the moment we have include five chronic diseases and tobacco use for Puerto Rico using the population based survey the Behavioral Risk Factor Surveillance Survey. We will continue expanding the outcomes as possible and include other global targets and BRFSS participant sites.

 **Now, an important question, waht are you doing to reduce your risk towards attain a chronic disease?**
 
 **Remember, is your responsability too.**
