---
title: "Epidemics can be stoped?"
author: "José A. Bartolomei-Díaz, PhD - Outcome Project"
date: "11/10/2014"
output: html_document
runtime: shiny
---

Due to the emergence of Chikungunya and Ebola many question has arise on how we can stop the spread of these and other diseases.  The most is important thing to understand is that throught the study of the the dynamics of infectious diseases by the pulic health reponse workers and the implementation of their recomendation by the general population is possible to reduce the risks of epidemics.  

A Disease is a consequence of an intruding agent (virus, parasite, bacteria, chemicals) to a person or animal making them sick. Sikness come when the ability of cells or tissues are compromised to perform a normal physiological process due to loss or damage of key functional molecules or cell.  The biological agents has always been part of our environment and are fighting for their ouwn surviaval in this world. When a micro-organism enters a host (ex. human body) start a replication process within the host system.  This process is call infection causing or not the person to be sick.

In this blog lets focus on viruses such as the Chikungunya and Ebola. A virus can only replicate withing the host (human or animals) although they can live outside of them for a period of time depending of the virus. When this micro-organism replicate witin the hospitable environment is call infection. A disease start when the host get symptomatic (sick).  Furthermore, we can have asymptomatic infection or symptomatic infection. An the infected person can be infectious meaning that the host (human) can infect others and is when trasmission occurs.  Furthermore, the infectious period is the length of time a host is able to trasmit the organism to others. This period is usefull to undrestand the propeties of epidemics. An infectious agent needs a hostpitable environment to replicate. For that reason is so important to have a healthy live for boosting the inmune system.

There are two type of transmission of infectious agents, the direct and the indirect.
Ebola is a pathogent with a direct trasmission meaning that it can pass from person to person directly using some form of transport such as body fluids.  In the other hand, Chikungunya need an intermediator named a vector which is a mosquito.  Other viruses uses other living animals such as the fly or rat among others to pass from one perons to another.  Other intermediates can be objects such as door knots and water which is a carrier for cholera.

Answer how epidemic starts and growth is difficult but can be simulated by mathematical parameters. But the most important strategy to follow if is desiere to stop diseases from spreading is to break the chain of stransmission. The only way to do that is understanding the pathogen transmission mechanism. Now, to understand how a pathogen present in a population can become an epidemic is important to understand certain epidemiological concepts.

The first person to be infected in a population or case 0 needs to pass the pathongen for an epidemic to start. It could be said when the number of infected persons increase exponentially we would have an epidemic which can be described by what is call the Reproductive Number, R0.

R0 is the average number of secondary infection generated by the first infectious individual in a popualation of completally suceptible individuals. Furthermore, understanding the process that limits the transmission process are needed to reduce R0. If the basic reproductive number is higher than one the risk of an epidemic increase.

Furthermore, To reduce the reproductive number (R0) is important to:

First, shorten the length of transmission (L) of an infectious host. Meaning the longer an individual is infectious the longer can transmit the agent to others. Moreover, R0 will increase with a longer length of infectious host.

Second, reduce the number of suceptible host (S). The greater the potential the first individual to transmit the infectious agent when increase the suceptibles. With the length of transmission and the number of suceptibles hosts S is possible to calculate the Potential Number of Contacts (C) over the course of an infection, C = L * S 

Finnally, is important to reduce the transmissibility (Beta) wich is a property of both the pathogent and the population.

	a. What is the rate of potentially transmissible contacts?
	b. How likely is a transmissable contact to result in successful tranmission?

With the mentioned dynamic parameters we can obtain the basic reproductive number to observe an epidemic: R0 = S * L * Beta.  An Oubreak is likely to spread if R0 is greater than one.

Now the question important question, how we can stop an outbreak? The answer is by:

1. Reducing the number of suceptible individual through vaccination or because those infected die or recover and get inmune.
2. Reducing the length of time an indiviual is infectious by asking ill people to stay at home.
3. Reducing the transmissibility by limiting contact or introducing sanitary measures. 

Althought the answer to control epidemics is quite simple it is really difficult to implement due to it require a extereme coordinated effort by the public helath authorities and the general population. More difficult it becames when vecotors difficult to control are a mode of transmission or public health strategies are hard to implement such as population quarantine.

Nevertheless, the most important of this blog is that is possible to prevent or control epidemics.





R0 is a measure of the average / expected outcome of transmission.
All this factor vary by person to person.

Usefull carateristic to generalize about an Outbreak the specific may depend on were and whom the first cases appears.

Epidemic curve

SIR compartametal framework
This is use to understand the epidemic curve 

Suceptible 
Infected 
Removed from the chain of infection: Death or inmume

Speed of increase of transmission depend on the R0 and the infectious period.
The higher the R0 and the shorter the infectious period the more explosive the infection is

Re = The effective reproductive number = R0 * fraction of susceptible population

```{r, echo=FALSE}
shinyAppDir(
  "/media/truecrypt2/Blog/Dynamic_of_ID/Shiny_R0",
  options=list(
    width="100%", height=550
  )
)
```



